### ISSUE TITLE
Wrong class name in Hello.ts.

### ISSUE THREAD

**Issue by lmrnfc** [StepanZharychev/vue-ts-webpack#2]
Wrong class name in Hello.ts, it works but this wrong name is displayed in Vue extension.
![screenshot_classname](https://user-images.githubusercontent.com/28565632/31379191-4e0b7aac-adb6-11e7-829c-3f2ee7ef707b.png)

**Comment by StepanZharychev** [comment]
Hmm, that's a bit unexpected, what's exactly wrong in name of component?
I mean you can name them whatever you like, it just should make sense.

**Comment by lmrnfc** [comment]
Both component declared as class MainComponent, and in Vue extension for debugging in Chrome this names are shown in components tree, it can confuse.

**Comment by StepanZharychev** [comment]
Anyways you're right, I'll fix this name. It can truly confuse. Thank you!
