### ISSUE TITLE
Better description for the project

### ISSUE THREAD

**Issue by AndrewBogdanovTSS** [StepanZharychev/vue-ts-webpack#3]
I've stumbled upon this project some time ago and found it great as a base for Vue-TS app. But the README.MD for it is too minimal. Could you add some more information describing what this project does and maybe a link to the original tutorial where you are describing overall setup?

**Comment by StepanZharychev** [comment]
Originally this example was done for [this article](https://habrahabr.ru/post/330400/). But if you describe the difficulties, that you've had during the set up, I'll include them into detailed READ.MD.
Thank you for feedback.
